# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-02 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('speed', models.CharField(max_length=20)),
                ('acceleration', models.CharField(max_length=20)),
                ('direction', models.CharField(max_length=20)),
                ('distance', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
